#ifndef _CONTROL_BORARD_H_
#define _CONTROL_BORARD_H_

#define FW_VERSION		0x10

#define LED1	R_PORT3->PODR_b.PODR3
#define LED2	R_PORT3->PODR_b.PODR4
#define LED3	R_PORT1->PODR_b.PODR13

#define CAN_SILENT	R_PORT0->PODR_b.PODR15

#define RS485_REB	R_PORT2->PODR_b.PODR4
#define RS485_DE	R_PORT4->PODR_b.PODR0

#define INT_PRIORITY_SCI0_TX		(0x08)
#define INT_PRIORITY_SCI0_RX		(0x08)


#endif /*_CONTROL_BORARD_H_*/
